fix shards
AlexeySetevoi/ansible-clickhouse pull request #67
Opened 2021-12-01 14:57 UTC by hruljov

2022-01-12 09:20 UTC, AntonFriberg commented
@AlexeySetevoi Could we perhaps retrigger the tests on this one? They seem related to #71

2022-01-12 14:29 UTC, AlexeySetevoi commented
Yes, the failed tests in this PR are associated with #71.
Since #71 changed the test declaration, this PR needs to be rebased to master.
Manual restart in this current PR state - will just fall again.

2022-03-17 16:36 UTC, AntonFriberg commented
@AlexeySetevoi This needs approval from you in order to run CI tests

2022-03-17 16:37 UTC, AntonFriberg commented on README.md
> +<<<<<<< HEAD
This looks like a misstake due to merge conflict

2022-03-17 16:37 UTC, AntonFriberg commented on README.md
> +>>>>>>> 7cb5558ba9f17238a4f33d2ba3b0f5e7c6ed7003
This also looks weird

2022-03-17 16:40 UTC, AntonFriberg requested changes
Saw some issues with this that I would guess Alexey would want fixed before he can merge this. Let me know if you have any questions.

2022-03-22 12:36 UTC, AntonFriberg commented
@AlexeySetevoi Could you start the CI tests on this one?

2022-03-23 08:30 UTC, hruljov commented
@AlexeySetevoi merge?

2022-03-23 08:31 UTC, merged